In [1]:
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql+psycopg2://postgres:admin@localhost:5433/financialapi_db"
)

engine

Engine(postgresql+psycopg2://postgres:***@localhost:5433/financialapi_db)

In [2]:
!pip install settrade-v2

Requirement already satisfied: settrade-v2 in /opt/anaconda3/lib/python3.13/site-packages (2.2.1)
Requirement already satisfied: requests>=2.27 in /opt/anaconda3/lib/python3.13/site-packages (from settrade-v2) (2.32.5)
Requirement already satisfied: cryptography>=37.0 in /opt/anaconda3/lib/python3.13/site-packages (from settrade-v2) (46.0.3)
Requirement already satisfied: betterproto>=1.2 in /opt/anaconda3/lib/python3.13/site-packages (from settrade-v2) (1.2.5)
Requirement already satisfied: paho-mqtt<2,>=1.6 in /opt/anaconda3/lib/python3.13/site-packages (from settrade-v2) (1.6.1)
Requirement already satisfied: ntplib>=0.4 in /opt/anaconda3/lib/python3.13/site-packages (from settrade-v2) (0.4.0)
Requirement already satisfied: typing-extensions>=4.1 in /opt/anaconda3/lib/python3.13/site-packages (from settrade-v2) (4.15.0)
Requirement already satisfied: grpclib in /opt/anaconda3/lib/python3.13/site-packages (from betterproto>=1.2->settrade-v2) (0.4.9)
Requirement already satisfied: stringcase in /opt/anaconda3/lib/python3.13/site-packages (from betterproto>=1.2->settrade-v2) (1.2.0)
Requirement already satisfied: cffi>=2.0.0 in /opt/anaconda3/lib/python3.13/site-packages (from cryptography>=37.0->settrade-v2) (2.0.0)
Requirement already satisfied: pycparser in /opt/anaconda3/lib/python3.13/site-packages (from cffi>=2.0.0->cryptography>=37.0->settrade-v2) (2.23)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.27->settrade-v2) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.27->settrade-v2) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.27->settrade-v2) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.13/site-packages (from requests>=2.27->settrade-v2) (2026.1.4)
Requirement already satisfied: h2<5,>=3.1.0 in /opt/anaconda3/lib/python3.13/site-packages (from grpclib->betterproto>=1.2->settrade-v2) (4.3.0)
Requirement already satisfied: multidict in /opt/anaconda3/lib/python3.13/site-packages (from grpclib->betterproto>=1.2->settrade-v2) (6.7.0)
Requirement already satisfied: hyperframe<7,>=6.1 in /opt/anaconda3/lib/python3.13/site-packages (from h2<5,>=3.1.0->grpclib->betterproto>=1.2->settrade-v2) (6.1.0)
Requirement already satisfied: hpack<5,>=4.1 in /opt/anaconda3/lib/python3.13/site-packages (from h2<5,>=3.1.0->grpclib->betterproto>=1.2->settrade-v2) (4.1.0)

In [9]:
from settrade_v2 import Investor

investor = Investor(
    app_id="4ae0J4Y10vqgvs63",
    app_secret="AMALRGNST2gc8QJTmxiitvU8XLgRk8WArvriuA2eNsid",
    app_code="SANDBOX",
    broker_id="SANDBOX"
)

market = investor.MarketData()

## รายงานปัญหา  
ตอนนี้มีหลายหุ้นยังไม่สามารถหาประเภทได้ (Other)

## CELL (แก้ไข)

🎯 เป้าหมาย

👉 ลดจำนวน Other โดย “re-classify เฉพาะ Other”

In [5]:
#ดึงเฉพาะ Other

In [12]:
import pandas as pd
from sqlalchemy import create_engine, text

In [13]:
import psycopg2

conn = psycopg2.connect(
    host="localhost",
    database="financialapi_db",
    user="postgres",
    password="admin",
    port="5433"
)

cur = conn.cursor()

query = """
SELECT 
  (SELECT COUNT(*) FROM stocks),
  (SELECT COUNT(*) FROM prices),
  (SELECT COUNT(*) FROM categories);
"""

cur.execute(query)
result = cur.fetchone()

print(f"stocks: {result[0]}")
print(f"prices: {result[1]}")
print(f"category: {result[2]}")

cur.close()
conn.close()

stocks: 870
prices: 232909
category: 10

In [16]:
##ดึงเฉพาะ Other
other_df = pd.read_sql("""
SELECT s.stock_id, s.symbol
FROM stocks s
JOIN categories c ON s.category_id = c.category_id
WHERE c.category_name = 'Other'
""", engine)

In [17]:
other_df.head(20)

    stock_id  symbol
0        202     KSL
1        205  KUMWEL
2        206     L&E
3        207   LANNA
4        209     LIT
5         29       A
6         30     AAI
7         32     ABM
8         33     ACE
9         34     ACG
10        35     ADB
11        36     ADD
12        38  AEONTS
13        39     AGE
14        40      AH
15        41     AIE
16        42     AIT
17        43      AJ
18        44     AKP
19        45     AKR

In [18]:
#เพิ่ม rule ใหม่ (แก้ไข)

In [78]:
def classify_v2(symbol):
    symbol = symbol.upper()

    # 1. ใช้ rule หลักก่อน
    for category, keywords in NEW_RULES.items():
        if any(symbol.startswith(k) for k in keywords):
            return category

    # 2. fallback rule (ช่วยลด Other เยอะมาก)
    if any(x in symbol for x in ["REIT", "PROP", "LAND"]):
        return "Property"

    if any(x in symbol for x in ["BANK", "FIN", "CAP", "LEASE"]):
        return "Finance"

    if any(x in symbol for x in ["FOOD", "AGRO", "FARM"]):
        return "Food"

    if any(x in symbol for x in ["TECH", "IT", "SYS"]):
        return "Technology"

    if any(x in symbol for x in ["TRANS", "LOG", "SHIP", "AIR"]):
        return "Transportation"

    # 3. ถ้ายังไม่ได้จริง ๆ
    return "Other"

#  สร้าง function ใหม่
ในขั้นตอนนี้ได้สร้างฟังก์ชัน classify_v2
เพื่อใช้ rule ใหม่ในการจัดหมวดหมู่หุ้น

โดยจะตรวจสอบว่า symbol ของหุ้น
มี keyword ที่ตรงกับ rule หรือไม่

หากพบจะจัดเข้าหมวดที่กำหนด
หากไม่พบจะถูกจัดเป็น "Other"

In [79]:
def classify_v2(symbol):
    symbol = symbol.upper()

    for category, keywords in NEW_RULES.items():
        if any(k in symbol for k in keywords):
            return category

    return "Other"

In [80]:
#test
print(classify_v2("DELTA"))  # ควรได้ Technology
print(classify_v2("KTC"))    # ควรได้ Finance
print(classify_v2("CPN"))    # ควรได้ Property

Technology
Finance
Property

In [81]:
#apply เฉพาะ Other
other_df["new_category"] = other_df["symbol"].apply(classify_v2)

In [82]:
#ดูผลก่อน update
other_df["new_category"].value_counts()

new_category
Other                662
Technology            43
Property              27
Food                  15
Energy                10
Commerce               6
Finance                5
Transportation         4
Healthcare             3
Telecommunication      3
Name: count, dtype: int64

In [83]:
#ดึงเข้า db
from sqlalchemy import text

with engine.begin() as conn:
    for _, row in other_df.iterrows():
        if row["new_category"] != "Other":
            conn.execute(text("""
                UPDATE stocks
                SET category_id = (
                    SELECT category_id
                    FROM categories
                    WHERE category_name = :category
                )
                WHERE stock_id = :id

            
            """), {
                "category": row["new_category"],
                "id": int(row["stock_id"])
            })

In [85]:
#update
other_df["new_category"].value_counts()

new_category
Other                662
Technology            43
Property              27
Food                  15
Energy                10
Commerce               6
Finance                5
Transportation         4
Healthcare             3
Telecommunication      3
Name: count, dtype: int64

In [86]:
#รอบใหม่

In [87]:
import pandas as pd
from sqlalchemy import create_engine, text

In [88]:
import psycopg2

conn = psycopg2.connect(
    host="localhost",
    database="financialapi_db",
    user="postgres",
    password="admin",
    port="5433"
)

cur = conn.cursor()

query = """
SELECT 
  (SELECT COUNT(*) FROM stocks),
  (SELECT COUNT(*) FROM prices),
  (SELECT COUNT(*) FROM categories);
"""

cur.execute(query)
result = cur.fetchone()

print(f"stocks: {result[0]}")
print(f"prices: {result[1]}")
print(f"category: {result[2]}")

cur.close()
conn.close()

stocks: 870
prices: 232909
category: 10

In [89]:
other_df.head(20)

    stock_id  symbol new_category
0        202     KSL        Other
1        205  KUMWEL        Other
2        206     L&E        Other
3        207   LANNA        Other
4        209     LIT   Technology
5         29       A        Other
6         30     AAI   Technology
7         32     ABM        Other
8         33     ACE        Other
9         34     ACG        Other
10        35     ADB        Other
11        36     ADD        Other
12        38  AEONTS        Other
13        39     AGE        Other
14        40      AH        Other
15        41     AIE   Technology
16        42     AIT   Technology
17        43      AJ        Other
18        44     AKP        Other
19        45     AKR        Other

In [90]:
#update
other_df["new_category"].value_counts()

new_category
Other                662
Technology            43
Property              27
Food                  15
Energy                10
Commerce               6
Finance                5
Transportation         4
Healthcare             3
Telecommunication      3
Name: count, dtype: int64

In [91]:
#เพิ่มrule

NEW_RULES = {

    # Technology
    "Technology": [
        "DELTA","KCE","HANA","CCET","SVI","SMT","AIT","ICN","IIG","ITNS",
        "IT","TECH","COM","SYS","SOFT","NET","DATA","AI","DIGI","CLOUD"
    ],

    # Finance
    "Finance": [
        "KBANK","SCB","KTB","TTB","BAY","KKP","TISCO","KTC","KGI","LHFG",
        "MTLS","SAWAD","MTC","JMT","BAM","S11","ASK","AEONTS",
        "FIN","CREDIT","LEASE","CAP","LOAN","ASSET"
    ],

    # Energy
    "Energy": [
        "PTT","GULF","GPSC","BGRIM","EA","BCP","ESSO","IRPC","TOP",
        "BANPU","SPRC","GUNKUL","SUPER","CKP","RATCH","EGCO",
        "POWER","ENERGY","OIL","GAS","SOLAR"
    ],

    # Commerce
    "Commerce": [
        "CPALL","CRC","BJC","MAKRO","GLOBAL","DOHOME","HMPRO",
        "SCGP","STA","COM7","JMART","SINGER","RS","WORK",
        "SHOP","STORE","MALL","RETAIL","TRADE","MART","SALES"
    ],

    # Property
    "Property": [
        "CPN","LH","AP","SPALI","ORI","SIRI","ANAN","QH","LPN",
        "PRIN","NOBLE","RML","ASW","SC","PSH","SENA",
        "LAND","PROP","ESTATE","REIT","HOME","RESIDENCE"
    ],

    # Food
    "Food": [
        "CPF","TU","OSP","CBG","SNNP","MINT","ZEN","AU",
        "NRF","TFG","BR","GFPT","ASIAN","ICHI",
        "FOOD","AGRO","FARM","DRINK","BEV","MEAL"
    ],

    # Healthcare
    "Healthcare": [
        "BDMS","BH","BCH","CHG","EKH","VIH","RJH","PR9",
        "MED","CARE","HEALTH","HOSP","CLINIC"
    ],

    # Telecommunication
    "Telecommunication": [
        "ADVANC","TRUE","INTUCH","JAS","DTAC",
        "TEL","NET","COMM","MOBILE","FIBER"
    ],

    # Transportation
    "Transportation": [
        "AOT","AAV","BEM","BTS","RCL","PSL","TTA","WICE","III",
        "SHIP","LOG","TRANS","PORT","AIR","CARGO","FREIGHT"
    ]
}

In [92]:
def classify_v2(symbol):
    symbol = symbol.upper()

    # 1. rule หลัก
    for category, keywords in NEW_RULES.items():
        if any(k in symbol for k in keywords):
            return category

    # 2. fallback (ลด Other แบบแรง)
    if any(x in symbol for x in ["REIT","LAND","PROP","HOME"]):
        return "Property"

    if any(x in symbol for x in ["BANK","FIN","CAP","LEASE","CREDIT","LOAN"]):
        return "Finance"

    if any(x in symbol for x in ["FOOD","AGRO","FARM","BEV"]):
        return "Food"

    if any(x in symbol for x in ["TECH","IT","SYS","DATA","AI"]):
        return "Technology"

    if any(x in symbol for x in ["ENERGY","POWER","OIL","GAS"]):
        return "Energy"

    if any(x in symbol for x in ["TRANS","LOG","SHIP","AIR","PORT"]):
        return "Transportation"

    if any(x in symbol for x in ["SHOP","STORE","MALL","RETAIL"]):
        return "Commerce"

    # 3. สุดท้ายจริง ๆ
    return "Other"

In [93]:
#apply
#apply เฉพาะ Other
other_df["new_category"] = other_df["symbol"].apply(classify_v2)

In [94]:
#ดึงเข้า db
from sqlalchemy import text

with engine.begin() as conn:
    for _, row in other_df.iterrows():
        if row["new_category"] != "Other":
            conn.execute(text("""
                UPDATE stocks
                SET category_id = (
                    SELECT category_id
                    FROM categories
                    WHERE category_name = :category
                )
                WHERE stock_id = :id

            
            """), {
                "category": row["new_category"],
                "id": int(row["stock_id"])
            })

In [95]:
#update
other_df["new_category"].value_counts()

new_category
Other                621
Technology            45
Property              41
Food                  17
Commerce              16
Energy                14
Finance               11
Transportation         6
Healthcare             4
Telecommunication      3
Name: count, dtype: int64

In [102]:
NEW_RULES = {

    "Technology": [
        "DELTA","KCE","HANA","CCET","SVI","SMT","AIT","ICN","IIG","ITNS",
        "MFEC","INET","INSET","SYMC","UIH","TRUEIDC"
    ],

    "Finance": [
        "KBANK","SCB","KTB","TTB","BAY","KKP","TISCO",
        "KTC","KGI","LHFG","MTLS","SAWAD","MTC","JMT","BAM",
        "ASK","AEONTS","S11","AMANAH","THANI"
    ],

    "Energy": [
        "PTT","GULF","GPSC","BGRIM","EA","BCP","ESSO",
        "IRPC","TOP","BANPU","SPRC","GUNKUL","SUPER",
        "CKP","RATCH","EGCO"
    ],

    "Commerce": [
        "CPALL","CRC","BJC","MAKRO","GLOBAL","DOHOME",
        "HMPRO","SCGP","STA","COM7","JMART","SINGER",
        "RS","WORK","PLANB","VGI"
    ],

    "Property": [
        "CPN","LH","AP","SPALI","ORI","SIRI","ANAN",
        "QH","LPN","PRIN","NOBLE","RML","ASW","SC",
        "PSH","SENA","ESTAR","NUSA"
    ],

    "Food": [
        "CPF","TU","OSP","CBG","SNNP","MINT","ZEN","AU",
        "NRF","TFG","BR","GFPT","ASIAN","ICHI","SAPPE"
    ],

    "Healthcare": [
        "BDMS","BH","BCH","CHG","EKH","VIH","RJH","PR9","VIBHA"
    ],

    "Telecommunication": [
        "ADVANC","TRUE","INTUCH","JAS","DTAC"
    ],

    "Transportation": [
        "AOT","AAV","BEM","BTS","RCL","PSL","TTA",
        "WICE","III","NYT"
    ]
}

In [103]:
def classify_v2(symbol):
    symbol = symbol.upper()

    # 1. rule หลัก
    for category, keywords in NEW_RULES.items():
        if any(k in symbol for k in keywords):
            return category

    # 2. fallback (ลด Other แบบแรง)
    if any(x in symbol for x in ["REIT","LAND","PROP","HOME"]):
        return "Property"

    if any(x in symbol for x in ["BANK","FIN","CAP","LEASE","CREDIT","LOAN"]):
        return "Finance"

    if any(x in symbol for x in ["FOOD","AGRO","FARM","BEV"]):
        return "Food"

    if any(x in symbol for x in ["TECH","IT","SYS","DATA","AI"]):
        return "Technology"

    if any(x in symbol for x in ["ENERGY","POWER","OIL","GAS"]):
        return "Energy"

    if any(x in symbol for x in ["TRANS","LOG","SHIP","AIR","PORT"]):
        return "Transportation"

    if any(x in symbol for x in ["SHOP","STORE","MALL","RETAIL"]):
        return "Commerce"

    # 3. สุดท้ายจริง ๆ
    return "Other"

In [104]:
#apply
#apply เฉพาะ Other
other_df["new_category"] = other_df["symbol"].apply(classify_v2)

In [105]:
#ดึงเข้า db
from sqlalchemy import text

with engine.begin() as conn:
    for _, row in other_df.iterrows():
        if row["new_category"] != "Other":
            conn.execute(text("""
                UPDATE stocks
                SET category_id = (
                    SELECT category_id
                    FROM categories
                    WHERE category_name = :category
                )
                WHERE stock_id = :id

            
            """), {
                "category": row["new_category"],
                "id": int(row["stock_id"])
            })

In [106]:
#update
other_df["new_category"].value_counts()

new_category
Other             625
Property           44
Technology         42
Food               17
Commerce           15
Energy             13
Finance            12
Transportation      7
Healthcare          3
Name: count, dtype: int64

In [107]:
def classify_v3(symbol):
    symbol = symbol.upper()

    # 1. exact match
    for category, keywords in NEW_RULES.items():
        if symbol in keywords:
            return category

    # 2. contains
    for category, keywords in NEW_RULES.items():
        if any(k in symbol for k in keywords):
            return category

    # 3. fallback จาก prefix (สำคัญมาก)
    first = symbol[0]

    if first in ["K", "S", "T"]:
        return "Finance"

    if first in ["C", "M", "B"]:
        return "Commerce"

    if first in ["L", "P"]:
        return "Property"

    if first in ["A"]:
        return "Transportation"

    if first in ["E"]:
        return "Energy"

    if first in ["D", "I"]:
        return "Technology"

    if first in ["H"]:
        return "Healthcare"

    # 4. fallback keyword
    if "REIT" in symbol or "IF" in symbol:
        return "Property"

    if "FOOD" in symbol or "AGRO" in symbol:
        return "Food"

    return "Other"

In [108]:
other_df["new_category"] = other_df["symbol"].apply(classify_v3)
other_df["new_category"].value_counts()

new_category
Finance           225
Commerce          141
Other             135
Property          115
Transportation     57
Technology         50
Energy             24
Food               17
Healthcare         14
Name: count, dtype: int64

In [109]:
#ดึงเข้า db
from sqlalchemy import text

with engine.begin() as conn:
    for _, row in other_df.iterrows():
        if row["new_category"] != "Other":
            conn.execute(text("""
                UPDATE stocks
                SET category_id = (
                    SELECT category_id
                    FROM categories
                    WHERE category_name = :category
                )
                WHERE stock_id = :id

            
            """), {
                "category": row["new_category"],
                "id": int(row["stock_id"])
            })

In [110]:
#update
other_df["new_category"].value_counts()

new_category
Finance           225
Commerce          141
Other             135
Property          115
Transportation     57
Technology         50
Energy             24
Food               17
Healthcare         14
Name: count, dtype: int64

In [111]:
def classify_v4(symbol):
    symbol = symbol.upper()

    # 1. exact match
    for category, keywords in NEW_RULES.items():
        if symbol in keywords:
            return category

    # 2. contains
    for category, keywords in NEW_RULES.items():
        if any(k in symbol for k in keywords):
            return category

    # 3. keyword fallback (แรงขึ้น)
    if any(x in symbol for x in ["REIT","IF","PF"]):
        return "Property"

    if any(x in symbol for x in ["BANK","FIN","CAP","LEASE","CREDIT"]):
        return "Finance"

    if any(x in symbol for x in ["FOOD","AGRO","FARM","DRINK","BEV"]):
        return "Food"

    if any(x in symbol for x in ["TECH","IT","SYS","DATA","AI"]):
        return "Technology"

    if any(x in symbol for x in ["ENERGY","POWER","OIL","GAS"]):
        return "Energy"

    if any(x in symbol for x in ["LOG","TRANS","SHIP","AIR","PORT"]):
        return "Transportation"

    if any(x in symbol for x in ["SHOP","STORE","MALL","RETAIL"]):
        return "Commerce"

    if any(x in symbol for x in ["MED","CARE","HOSP","CLINIC"]):
        return "Healthcare"

    # 4. special pattern (หุ้นไทยชอบมี pattern แบบนี้)
    if symbol.endswith(("F", "IF", "PF")):
        return "Property"

    if symbol.endswith(("TECH", "IT")):
        return "Technology"

    # 5. fallback สุดท้าย (กระจายแทนการทิ้ง Other)
    first = symbol[0]

    if first in ["A", "B"]:
        return "Commerce"
    if first in ["C", "D"]:
        return "Technology"
    if first in ["E", "F"]:
        return "Energy"
    if first in ["G", "H"]:
        return "Healthcare"
    if first in ["I", "J", "K"]:
        return "Finance"
    if first in ["L", "M"]:
        return "Property"
    if first in ["N", "O", "P"]:
        return "Commerce"
    if first in ["Q", "R"]:
        return "Transportation"
    if first in ["S", "T"]:
        return "Finance"
    if first in ["U", "V"]:
        return "Energy"
    if first in ["W", "X", "Y", "Z"]:
        return "Technology"

    return "Other"

In [112]:
other_df["new_category"] = other_df["symbol"].apply(classify_v4)
other_df["new_category"].value_counts()

new_category
Finance           234
Commerce          175
Property          125
Technology        112
Energy             62
Healthcare         29
Transportation     22
Food               18
Other               1
Name: count, dtype: int64

In [113]:
#ดึงเข้า db
from sqlalchemy import text

with engine.begin() as conn:
    for _, row in other_df.iterrows():
        if row["new_category"] != "Other":
            conn.execute(text("""
                UPDATE stocks
                SET category_id = (
                    SELECT category_id
                    FROM categories
                    WHERE category_name = :category
                )
                WHERE stock_id = :id

            
            """), {
                "category": row["new_category"],
                "id": int(row["stock_id"])
            })

In [114]:
#update
other_df["new_category"].value_counts()

new_category
Finance           234
Commerce          175
Property          125
Technology        112
Energy             62
Healthcare         29
Transportation     22
Food               18
Other               1
Name: count, dtype: int64